name: Lint Files

on: [pull_request]

jobs:
  build:
    if: contains('["AjrafDev"]', github.actor)
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.4.2"
      
      - name: step1
        run: |
          sqlfluff lint --format github-annotation --annotation-level failure --nofail > annotations.json
          
      - name: Annotate
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'lint-sql'
          input: './annotations.json'

      - name: step2
        id: vars1
        run: |
          sqlfluff lint --format github-annotation --annotation-level failure --nofail > annotations.json
          export OUTP=`sqlfluff lint --format human`
          OUTP2=$(echo $OUTP | cut -d "]" -f 2)
          echo $OUTP2
          echo test=$OUTP2 >> $GITHUB_OUTPUT
          
      - name: step3
        if: success() && steps.step1.outcome != 'failure'
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{steps.vars1.outputs.test}}
          allow-repeats: true

