name: Lint Files

on: [pull_request]

jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.4.2"
    
      - name: Lint files
        id: lint-files
        run: "sqlfluff lint"
        
      - name: action-lint-failure
        if: failure() && steps.lint-files.outcome != 'success'
        run: echo "SQL file failed Syntax checks"

      - name: action-lint-success
        if: success() && steps.lint-files.outcome != 'failure'
        uses: peter-evans/create-or-update-comment@v2
          with:
            issue-number: 1
            body: echo "SQL file passed Syntax checks"
        
