name: Lint Files

on: [pull_request]

jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.4.2"
    
      - name: Lint files
        id: lint-files
        run: |
          touch output.txt
          sqlfluff lint > output.txt
        
      - name: action-lint-failure
        if: failure() && steps.lint-files.outcome != 'success'
        uses: maxkomarychev/octions/octions/issues/create-comment@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          body: FILE::output.txt
            
      - name: action-lint-success
        if: success() && steps.lint-files.outcome != 'failure'
        uses: jungwinter/comment@v1
        id: create2
        with:
          type: create
          body: "SQL file passed syntax checks"
          issue_number: '1'
          token: ${{ secrets.GITHUB_TOKEN }}
