name: Lint Files

on: [pull_request]

jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.4.2"
    
      - name: Lint files
        id: lint-files
        run: sqlfluff lint > output.txt
      
      - name: Read file contents
        if: failure() && steps.lint-files.outcome != 'success'
        id: readcon
        run: echo "FILE1=cat output.txt" >> $GITHUB_OUTPUT

      - name: File contents
        if: failure() && steps.lint-files.outcome != 'success'
        run: echo "${{ steps.raedcon.outputs.FILE1 }}"
          
        
        
      - name: action-lint-failure-file
        if: failure() && steps.lint-files.outcome != 'success'
        run: echo "hello"

                          
      - name: action-lint-success
        if: success() && steps.lint-files.outcome != 'failure'
        uses: jungwinter/comment@v1
        id: create2
        with:
          type: create
          body: "SQL file passed syntax checks"
          issue_number: '1'
          token: ${{ secrets.GITHUB_TOKEN }}
