name: Lint Files

on: [pull_request]

jobs:
  job1:
    outputs:
        output1: ${{ steps.step1.outputs.test }}
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.4.2"
    
      - name: Lint files
        id: lint-files
        run: |
          sqlfluff lint > output.txt --format github-annotation
      
      - name: step1
        if: failure() && steps.lint-files.outcome != 'success'
        run: |
          echo "$(<output.txt )"
          echo "test=cat output.txt" >> $GITHUB_OUTPUT

        
      - name: action-lint-failure-file
        if: failure() && steps.lint-files.outcome != 'success'
        uses: actions-ecosystem/action-create-comment@v1
        with:
          needs: job1
          github_token: ${{ secrets.github_token }}
          body: |
            ${{ needs.job1s.outputs.output1 }}!

                          
      - name: action-lint-success
        if: success() && steps.lint-files.outcome != 'failure'
        uses: jungwinter/comment@v1
        id: create2
        with:
          type: create
          body: "SQL file passed syntax checks"
          issue_number: '1'
          token: ${{ secrets.GITHUB_TOKEN }}
