name: Lint Files

on: [pull_request]

jobs:
  job1:
    outputs:
        output1: ${{ steps.step1.outputs.test }}
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.4.2"
      
      - name: step1
        run: |
          var=$(sqlfluff lint --format github-annotation)
          test=$var >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: action-lint-failure-file
        if: failure() && steps.step1.outcome != 'success'
        run: echo ${{needs.job1.outputs.output1}}
 
      - name: action-lint-success
        if: success() && steps.lint-files.outcome != 'failure'
        uses: jungwinter/comment@v1
        id: create2
        with:
          type: create
          body: "SQL file passed syntax checks"
          issue_number: '1'
          token: ${{ secrets.GITHUB_TOKEN }}
