name: Lint Files

on: [pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.4.2"
    
      - name: Lint files
        id: lint-files
        run: sqlfluff lint > output.txt --format github-annotation
      
      - name: Read file contents
        if: failure() && steps.lint-files.outcome != 'success'
        id: step1
        run: echo "test=cat output.txt" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: File contents
        run: echo ${{needs.job1.outputs.output1}}
          
