name: Lint Files

on: [pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.4.2"
      
      - name: step1
        id: vars1
        run: |
          echo $(sqlfluff lint --format human)
          declare OUTP=`sqlfluff lint --format human`
          echo test=$OUTP >> $GITHUB_OUTPUT
          echo $test | cut -d "]" -f 2
          
      - name: step2
        id: vars2
        if: success() && steps.step1.outcome != 'failure'
        run: |
          declare str=${{steps.vars1.outputs.test}}
          echo $str
          
      - name: step3
        if: success() && steps.step1.outcome != 'failure'
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{steps.vars.outputs.test}}
          allow-repeats: true
          
      - name: step4
        if: success() && steps.step1.outcome != 'failure'
        run: |
          declare vars=${{needs.job1.outputs.test}}
          echo $vars

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: action-lint-failure-file
        if: failure() && steps.step1.outcome != 'success'
        run: echo ${{needs.job1.outputs.output1}}
 
      - name: action-lint-success
        if: success() && steps.step1.outcome != 'failure'
        run: ${{needs.job1.outputs.output1}}
